apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@gitlab.com:deimosdev/playground/zim/month_3/argocd-apps-boutique.git
    path: microservices/adservice
    targetRevision: HEAD
  destination:
    namespace: argocd-boutique-app
    server: https://kubernetes.default.svc
